# config.toml

# Do not touch this value, it is used to identify the config file
config-version = 1

# ignored if 'KEY' env variable is set
token = "123456789:ABC-DEF1234ghIkl-zyx57W2v1u123ew11"

[explicit-control]
# false if ask every start
enabled = true
# "web" if only web control
# "cli" if only terminal control
type = "web"



